version: "3.8"
services:
  api-gateway:
    image: api-gateway:latest
    
    ports:
      - "2000:2000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - PAYMENT_SERVICE_URL=http://payment-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
      - TUITION_SERVICE_URL=http://tuition-service:3005
    depends_on:
      - auth-service
      - user-service
      - payment-service
      - notification-service
      - tuition-service

  auth-service:
    image: auth-service:latest
    
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-db
    depends_on:
      - mongo

  user-service:
    image: user-service:latest
    
    
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-db
    depends_on:
      - mongo

  payment-service:
    image: payment-service:latest
    
    
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/payment-db
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  notification-service:
    image: notification-service:latest
    
    environment:
      - MONGO_URI=mongodb://mongo:27017/notification-db
      - EMAIL_USER=minhtuank27tdtu@gmail.com
      - EMAIL_PASS=scxwnfestbszztcf
      - OTP_EXPIRE_MINUTES=1
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    deploy:
      replicas: 3 # Số lượng bản sao
      restart_policy:
        condition: on-failure

  frontend:
    image: frontend:latest
    
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  tuition-service:
    image: tuition-service:latest
    
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tuition-db
    depends_on:
      - mongo
      
  
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  rabbitmq-data:

